version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fa_app_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8088:8088"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: fa_redis_container
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  redis_data:
